first version of conanfile.py, issue#38
erikzenker/inotify-cpp pull request #82
Opened 2021-08-18 12:34 UTC by dannftk

Provide first version of conanfile.py

Resolves [issue#38](https://github.com/erikzenker/inotify-cpp/issues/38)

Signed-off-by: Denis Pronin <dannftk@yandex.ru>

2021-08-18 21:01 UTC, erikzenker requested changes
Thank you for your contribution :-)

2021-08-18 21:01 UTC, erikzenker commented on conanfile.py
> +    name = "inotifycpp"
it is `inotify-cpp`

2021-08-19 03:46 UTC, dannftk commented on test/unit/CMakeLists.txt
> +          CONAN_PKG::boost
Where have you seen such an approach?

2021-08-24 19:53 UTC, erikzenker commented on test/unit/CMakeLists.txt
> +          CONAN_PKG::boost
https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html

2022-03-11 08:18 UTC, closed without merging